doctoronline/urls.py
from doctoronline.settings import MEDIA_ROOT
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("doctoronline/",include("doctoronlinemaster.urls")),
]+static(settings.MEDIA_URL,document_root=MEDIA_ROOT)

doctoronlinemaster/urls.py
from django.urls import path
from .views import *

app_name="doctoronlinemaster"

urlpatterns=[
    path("",homeView,name="home"),
    path("patientlogin/",patientLogin,name="patientlogin"),
    path("doctorlogin/",doctorLogin,name="doctorlogin"),
    path("signup/",signupView,name="signup"),
    path("login/",login,name="login"),
    path("signuppatient/",signUpViewPatient,name="signuppatient"),
    path("dashboard/<int:user_id>/",dashboard,name="dashboard"),
    path("userdashboard/<int:user_id>/",userDashboard,name="userdashboard"),
    path("getJson/",getJson,name="getjson"),
    path("getJsonTest/",getJsonView,name="getJsonTest"),
    path("getspecialist/",getSpecialist,name="getspecialist"),
    path("makeappointment/",makeAppointment,name="makeappointment"),
    path("deletepatientmessage/",deletePatientMessage,name="deletepatientmessage"),
    path("deletePatientAppointment/",deletePatientAppointment),
    path("ambulancedetails/",getAmbulanceDetails),
    path("bookambulance/",bookAmbulance),
]

doctoronlinemaster/views.py
from django.core.checks import messages
from django.http import response
from django.http.request import HttpRequest
from django.http.response import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Ambulance, Ambulance_Orders, Appointment, AppointmentTypes, HomeCare, HomeCareServices, MainSliderImages,Partiners,About, PatientAppointments,Specialization,UserPatient,LoginPatient,Countries,UserSpecialist,SpecialistLogin,PatientMessages,SpecialistMessages
from django.urls import reverse
import requests
import datetime
from datetime import time,timedelta,date
import random

def homeView(request):
    mainsliderimages=MainSliderImages.objects.all()
    partiners=Partiners.objects.all()
    about=About.objects.all()
    if about.count() > 0 :
          doctoronlineabout=about[0]
    else:
         doctoronlineabout="Add Description About Your Platform so as users to Know You better."
    return render(request,"doctoronlinemaster/main.html",
    {"mainsliderimages":mainsliderimages,"partiners":partiners,"about":doctoronlineabout,})

def patientLogin(request):
    if request.method == "POST":
        email=request.POST.get("email")
        password=request.POST.get("password")
        if email and password:
            try:
                userPatient=UserPatient.objects.get(email=email)
                userPatientLogin=LoginPatient.objects.get(userPatient=userPatient,password=password)
            except UserPatient.DoesNotExist:
                loginerrorMsg="Such user Does not exist. Create an Account to Access our Services"
                return  render(request,"doctoronlinemaster/login.html",{"loginErrorMsg":loginerrorMsg,})
            except LoginPatient.DoesNotExist:
                loginerrorMsg="Password Incorrect. Try Again or Reset Password"
                return  render(request,"doctoronlinemaster/login.html",{"loginErrorMsg":loginerrorMsg,})
            else:
                return HttpResponseRedirect(reverse("doctoronlinemaster:userdashboard",args=(userPatient.pk,)))

    return render(request,"doctoronlinemaster/login.html")

def doctorLogin(request):
    if request.method == "POST":
        email=request.POST.get("doctor_email")
        password=request.POST.get("doctor_password")
        if email and password:
            try:
                userSpecialist=UserSpecialist.objects.get(email=email)
                userPatientLogin=SpecialistLogin.objects.get(userSpecialist=userSpecialist,password=password)
            except UserSpecialist.DoesNotExist:
                loginerrorMsg="Such user Does not exist. Create an Account to Access our Services"
                return  render(request,"doctoronlinemaster/login.html",{"loginErrorMsg":loginerrorMsg,})
            except SpecialistLogin.DoesNotExist:
                loginerrorMsg="Password Incorrect. Try Again or Reset Password"
                return  render(request,"doctoronlinemaster/login.html",{"loginErrorMsg":loginerrorMsg,})
            else:
                return HttpResponseRedirect(reverse("doctoronlinemaster:dashboard",args=(userSpecialist.pk,)))

    return render(request,"doctoronlinemaster/login.html")


def signUpViewPatient(request):
    countries=[country.name for country in Countries.objects.all()]
    cities=[country.capital for country in Countries.objects.all() ]
    if request.method=="POST":
        email=request.POST.get("email")
        password=request.POST.get("password")
        try:
            user=UserPatient.objects.get(email=email)
            if user:
                usererror="User Already Exists. Reset Password or create another account with another Email"
                return render(request,"doctoronlinemaster/signup.html",{"usererror":usererror,"countries":countries,"cities":cities,})
        except UserPatient.DoesNotExist:
            if email and  password :
                userPatient=UserPatient(email=email)
                userPatient.save()
                userPatientLogin=LoginPatient(userPatient=userPatient,password=password)
                userPatientLogin.save()
                return HttpResponseRedirect(reverse("doctoronlinemaster:userdashboard",args=(userPatient.pk,)))
    
    return render(request,"doctoronlinemaster/signup.html",{"currentindex":False,"countries":countries,"cities":cities})
    
def signupView(request):
    countries=[country.name for country in Countries.objects.all()]
    cities=[country.capital for country in Countries.objects.all() ]
    if request.method=="POST":
        fname=request.POST.get("doctor_fname")
        lname=request.POST.get("doctor_lname")
        email=request.POST.get("doctor_email")
        password=request.POST.get("doctor_password")
        country=request.POST.get("country")
        city=request.POST.get("city")
        phone=request.POST.get("doctor_phone")
        try:
            user=UserSpecialist.objects.get(email=email)
            if user:
                usererror="User Already Exists. Reset Password or create another account with another Email"
                return render(request,"doctoronlinemaster/signup.html",{"currentindex":True,"usererror":usererror,"countries":countries,"cities":cities,})
        except UserSpecialist.DoesNotExist:

            if email and  password :
               userSpecialist=UserSpecialist(first_name=fname,last_name=lname,email=email,country=country,city=city,phone=phone)
               userSpecialist.save()
               userSpecialistLogin=SpecialistLogin(userSpecialist=userSpecialist,password=password)
               userSpecialistLogin.save()
               return HttpResponseRedirect(reverse("doctoronlinemaster:dashboard",args=(userSpecialist.pk,)))
    
    return render(request,"doctoronlinemaster/signup.html",{"currentindex":False,"countries":countries,"cities":cities})

def login(request):
    return render(request,"doctoronlinemaster/login.html")

## specialist dashboard
def dashboard(request,user_id):
     
     user=UserSpecialist.objects.get(pk=user_id)
     try:
         profile_img=user.profile_photo.url
         profile_img=True
     except:
         profile_img=False

     assignedambulances=Ambulance_Orders.objects.filter(assigned_specialist=user)
     allhomecareservices=HomeCare.objects.filter(supervisor=user)
     activehomecare=HomeCare.objects.filter(supervisor=user).filter(end_date__gte=date.today())
     activeassignedambulances=Ambulance_Orders.objects.filter(assigned_specialist=user).filter(end_time__gte=datetime.datetime.now())
     activeappointments=Appointment.objects.filter(specialist=user).filter(end_time__gte=datetime.datetime.now())
     allappointments=Appointment.objects.filter(specialist=user)
     return render(request,"doctoronlinemaster/dashboard.html",
     {"activeappointments":activeappointments,"allappointments":allappointments,
     "assignedambulances":assignedambulances,"activeassignedambulances":activeassignedambulances,
     "allhomecareservices":allhomecareservices,"activehomecare":activehomecare,"profile_img":profile_img,"user":user,})

##end of specialist dashboard

def userDashboard(request,user_id):
    specialists={}
    
    user=UserPatient.objects.get(pk=user_id)
    messages=PatientMessages.objects.filter(user=user).order_by("-datePosted")
    ambulances=Ambulance.objects.all()
    allhomecareservices=HomeCare.objects.filter(patient=user)
    activehomecareservices=HomeCare.objects.filter(end_date__gte=date.today())
    allambulanceorders=Ambulance_Orders.objects.filter(userPatient=user)
    currentamulanceorder=Ambulance_Orders.objects.filter(userPatient=user).filter(end_time__gte=datetime.datetime.now())
    appointments=PatientAppointments.objects.filter(patient=user)
    activeappointments=PatientAppointments.objects.filter(end_time__gte=datetime.datetime.now()).order_by("start_time")

    for sc in Specialization.objects.all():
        if sc.userspecialist_set.all().count() > 0:
            specialists[sc.type]=sc.userspecialist_set.all()
    return render(request,"doctoronlinemaster/userdashboard.html",{"specialists":specialists,"ambulances":ambulances,
    "user":user,"messages":messages,"appointments":appointments,"activeappointments":activeappointments,
    "ambulanceorders":allambulanceorders,"activeambulanceorders":currentamulanceorder,
    "allhomecareservices":allhomecareservices,"activehomecareservices":activehomecareservices,})


def getSpecialist(request):
     specialist_id=request.GET["specialist_id"]
     try:
         specialist=UserSpecialist.objects.get(pk=specialist_id)
         f_name=specialist.first_name
         l_name=specialist.last_name
         phone=specialist.phone
         email=specialist.email
         about=specialist.about
         country=specialist.country
         city=specialist.city
         specialization=[]
         typeOfAppointment=[[sp.type,sp.price,sp.pk] for sp in AppointmentTypes.objects.filter(specialist=specialist)]
         activeappointments=[sp.end_time for sp in specialist.appointment_set.filter(end_time__gte=datetime.datetime.now())]
         
         
         for s in specialist.specialization.all():
                specialization.append(s.type)
         specialistDetails={
            "first_name":f_name,
            "last_name":l_name,
            "email":email,
            "phone":phone,
            "about":about,
            "country":country,
            "city":city,
            "specialization":specialization,
            "active_appointments":activeappointments,
            "typeOfAppointment":typeOfAppointment
        }
         return JsonResponse({"specialistData":specialistDetails},safe=False)
     except UserSpecialist.DoesNotExist:
         return JsonResponse({"data":"none"},safe=False)

    
def makeAppointment(request):
    sId=request.POST.get("specialist_id")
    apType=request.POST.get("appointment_type")
    apId=request.POST.get("appointment_id")

doctoronlinemaster/templates/doctoronlinemaster/ajax.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajax Requests</title>
    {% load static %}
    <script src="{% static 'doctoronlinemaster/jquery-3.5.1.js' %}"></script>
</head>
<body>
    <script>
        $(document).ready(function(){
            $.ajax({
                url: "/doctoronline/getJson/",
                method: "GET",
                data:{
                    "mydata":"Alex Muthini",
                },
                dataType: "JSON"
            })
            .done(function(data){
               var objects=data["about"]
               console.log(JSON.stringify(objects));
                // objects.forEach(element => {
                    
                //         $("<img>").attr({
                //             id:element["id"],
                //             src:"/mymedia/"+element["image"],
                //             width:"100",
                //             height:"100"
                //         }).appendTo("body")
                    
                // });
               
            // $("<h1>").text(myData).appendTo("body")
        })
        .fail(function(xhr,status,err){
            console.log("Error occured: ",err);
            console.log("status code: ",status);
            console.dir(xhr)
        })
        .always(function(){
            console.log("Request Finished");
        })
        })
        
    </script>
</body>
</html>

doctoronlinemaster/templates/doctoronlinemaster/enteremail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/bootstrap-5/css/bootstrap.min.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static '/fontawesome/css/all.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static '/doctoronlinemaster/login.css' %}">
    {% load static %}
    <script src="{% static '/doctoronlinemaster/popper.js' %}"></script>
    {% load static %}
    <script src="{% static '/bootstrap-5/js/bootstrap.min.js' %}"></script>

</head>
<body>
    <div class="container-fluid main-login-container h-100">
        <div class="login-container row align-items-center h-100 px-2">
                <div class="login-details col h-100 d-flex align-items-center">
                    <form action="{% url 'doctoronlinemaster:enterpassword' %}" class="d-flex bg-white h-75 w-100 p-2 flex-column rounded" method="POST">
                        {% csrf_token %}
                        <div class="input-container d-flex flex-column flex-md-row align-items-center mt-5">
                            <label for="" class="form-label fs-5">Email</label>
                            <input type="text" class="form-control p-2 m-2" placeholder="example@gmail.com">
                        </div>
                       <button class="btn btn-sm btn-primary mt-auto align-self-end" type="submit" style="width: max-content;">Next <i class="fas fa-chevron-right"></i></button>
                    </form>
                </div>
                <div class="login-container-right d-none d-sm-flex flex-column col h-75 p-5  text-light">
                      <p class="lead" style="font-size: large">
                          Online Platform That Gives You Access to wide range of Medical Services
                           And Emergency Response Services anywhere.
                      </p>
                      <p class="lead" style="font-size: 1.5em;">
                          You are a medial Institution and wish to reach more People This is the best Platform in the 
                          Market where you can reach greater Audience.
                      </p>
                      <button class="btn btn-lg btn-outline-primary mt-auto">Get Started <i class="fas fa-chevron-right"></i></button>
                </div>
        </div>
    </div>
</body>
</html>

doctoronlinemaster/templates/doctoronlinemaster/enterpassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/bootstrap-5/css/bootstrap.min.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static '/fontawesome/css/all.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static '/doctoronlinemaster/login.css' %}">
    {% load static %}
    <script src="{% static '/doctoronlinemaster/popper.js' %}"></script>
    {% load static %}
    <script src="{% static '/bootstrap-5/js/bootstrap.min.js' %}"></script>

</head>
<body>
    <div class="container-fluid main-login-container h-100">
        <div class="login-container row align-items-center h-100 px-2">
                <div class="login-details col h-100 d-flex align-items-center">
                    <form action="{% url 'doctoronlinemaster:home'%}" class="d-flex bg-white h-75 w-100 p-2 flex-column rounded" method="POST">
                        {% csrf_token %}
                        <div class="input-container d-flex flex-column flex-md-row align-items-center mt-5">
                            <label for="" class="form-label fs-5">Password</label>
                            <input type="password" class="form-control p-2 m-2" placeholder="your password">
                        </div>
                       <button class="btn btn-lg btn-primary mt-auto align-self-end" type="submit" style="width: max-content;"><fas class="fas fa-lock-open text-dark"></fas> Login </button>
                    </form>
                </div>
                <div class="login-container-right d-none d-sm-flex flex-column col h-75 p-5  text-light">
                      <p class="lead" style="font-size: large">
                          Online Platform That Gives You Access to wide range of Medical Services
                           And Emergency Response Services anywhere.
                      </p>
                      <p class="lead" style="font-size: 1.5em;">
                          You are a medial Institution and wish to reach more People This is the best Platform in the 
                          Market where you can reach greater Audience.
                      </p>
                      <button class="btn btn-lg btn-outline-primary mt-auto">Get Started <i class="fas fa-chevron-right"></i></button>
                </div>
        </div>
    </div>
</body>
</html>

doctoronlinemaster/templates/doctoronlinemaster/login.html
{% extends "doctoronlinemaster/main.html" %}
{% block maintitle %}
  Login
{% endblock maintitle %}

{% block otherstyles %}
   {% load static %}
   <link rel="stylesheet" href="{% static '/doctoronlinemaster/login22.css' %}">
{% endblock otherstyles %}

{% block mainslider%}
{% endblock mainslider %}

{% block maincontent %}
    <div class="container-fluid main-signup-container d-flex justify-content-center align-items-center p-1 p-sm-2">
        <div class="signup-container h-100 row align-items-center  px-1 px-md-2">
                <div class="signup-details col d-flex flex-column align-items-center justify-content-center p-2">
                    <ul class="nav nav-tabs rounded w-100" role="tablist" id="signuptablist"> 
                        <li class="nav-item dropdown w-100 bg-white rounded" role="presentation">
                            <a href="#account-type" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" arial-expanded="false" role="button">Account Type</a>
                            <ul class="dropdown-menu " id="account-type">
                                <li class="dropdown-item "><button class="nav-link border-0" type="button" data-bs-toggle="tab" role="tab" data-bs-target="#patients">Patient | Customer</button></li>
                                <li class="dropdown-item "><button class="nav-link border-0" type="button" data-bs-toggle="tab" role="tab" data-bs-target="#doctors">Doctors | Other Specialists</button></li>
                            </ul>
                            <!-- <button class="nav-link active" data-bs-toggle="tab" type="button" data-bs-target="#patients" role="tab">Patients | Customers</button> -->
                        </li>
                        <!-- <li class="nav-item" role="presentation">
                            <button class="nav-link" type="button" data-bs-toggle="tab" data-bs-target="#doctors" role="tab">Doctors | Other Specialists</button>
                        </li> -->
                    </ul>  
                    <div class="tab-content">
                        <div class="tab-pane fade {% if not currentindex %} show active  {% endif %} p-2 h-100" role="tabpanel" id="patients">
                            <form action="{% url 'doctoronlinemaster:patientlogin' %}" class="d-flex bg-white w-100 p-2 p-md-4 flex-column rounded position-relative" method="POST">
                                {%csrf_token%}
                                {% if loginErrorMsg %}
                                <div class="toast align-items-center text-white show bg-primary w-100 border-0 position-absolute bottom-100 start-0" id="loginerroralert" role="alert" aria-live="assertive" aria-atomic="true">
                                    <div class="d-flex justify-content-center align-items-center">
                                      <div class="toast-body">
                                        {{loginErrorMsg}}
                                      </div>
                                      <button type="button" class="btn-close btn-close-white me-2 m-auto" id="loginerrorBtnClose" data-bs-dismiss="toast" data-bs-target="#loginerroralert" aria-label="Close"></button>
                                    </div>
                                  </div>
                                {% endif %}
                                <div class="input-container d-flex flex-column flex-md-row align-items-center ">
                                  <label for="" class="form-label fs-5">Email</label>
                                  <input type="email" name="email" id="email" class="form-control p-2 m-2" placeholder="example@gmail.com">
                               </div>
                               <div class="input-container d-flex flex-column flex-md-row align-items-center">
                                <label for="" class="form-label fs-5">Password</label>
                                <input type="password" name="password" id="password" class="form-control p-2 m-2" placeholder="Password">
                               </div>
                                <div class="input-container d-flex justify-content-center align-items-center my-3">
                                    <a href="" class="text-primary fs-6 text-decoration-none">Forgot Password</a>
                                </div>
                              <button class="btn btn-lg btn-primary mt-3" type="submit">
                                Login <span class="text-warning" style="font-size: x-small;">patient|anonymous</span></button>
                            </form>
                        </div>
                        <div class="tab-pane fade {% if currentindex %} show active {% endif %}" role="tabpanel" id="doctors">
                            <form action="{% url 'doctoronlinemaster:doctorlogin' %}" class="d-flex position-relative bg-white w-100 p-2 mt-2 flex-column rounded" method="POST">
                                {%csrf_token%}
                                {% if usererror %}
                                <div class="toast align-items-center text-white show bg-primary w-100 border-0 position-absolute bottom-100 start-0" id="loginerroralertspecialist" role="alert" aria-live="assertive" aria-atomic="true">
                                    <div class="d-flex justify-content-center align-items-center">
                                      <div class="toast-body">
                                        {{usererror}}
                                      </div>
                                      <a href="{% url 'doctoronlinemaster:signup'%}" class="btn btn-lg btn-outline-primary mt-auto" role="button">Get Started <i class="fas fa-chevron-right"></i></a>
                                    </div>
                                  </div>
                                {% endif %}
                                <div class="input-container d-flex flex-column flex-md-row align-items-center">
                                   <label for="" class="form-label fs-5">Email</label>
                                   <input type="email" name="doctor_email" id="doctor_email"  class="form-control p-2 m-2" placeholder="example@gmail.com">
                                </div>
                                
                                   <div class="input-container d-flex flex-column flex-md-row align-items-center">
                                    <label for="" class="form-label fs-5">Password</label>
                                    <input type="password" name="doctor_password" id="doctor_password" class="form-control p-2 m-2" placeholder="Password">
                                   </div>
                                   <div class="input-container d-flex justify-content-center align-items-center my-3">
                                    <a href="" class="text-primary fs-6 text-decoration-none">Forgot Password</a>
                                  </div>
                                   <button class="btn btn-lg btn-primary mt-3" type="submit">
                                    Login <span class="text-warning" style="font-size: x-small;">Doctor|Specialist</span></button>
                             </form>
                        </div>
                    </div>
                    
                </div>
                <div class="login-container-right d-none d-sm-flex flex-column col  p-5  text-light">
                      <p class="lead" style="font-size: large">
                          Sign Up for an account to Access our services. 
                      </p>
                      <p class="lead" style="font-size: 1.5em;">
                          You are a medial Institution and wish to reach more People This is the best Platform in the 
                          Market where you can reach greater Audience.
                      </p>
                      <a href="{% url 'doctoronlinemaster:signup'%}" class="btn btn-lg btn-outline-primary mt-auto" role="button">Get Started <i class="fas fa-chevron-right"></i></a>
                </div>
        </div>
    </div>
    {% endblock maincontent %}

    {% block otherjs%}
    <script>
        var errorContainer=document.getElementById("loginerroralert");
        var errorBtnClose=document.getElementById("loginerrorBtnClose")
        errorBtnClose.addEventListener("click",function(){
            errorContainer.classList.remove("show")
            errorContainer.style="z-index:-1"
        })

        var specialistBtnClose=document.getElementById("loginerrorBtnCloseSpecialist")
        var specialistContainer=document.getElementById("loginerroralertspecialist")
        specialistBtnClose.addEventListener("click",function(){
            specialistContainer.classList.remove("show")
            specialistContainer.style="z-index:-1"
        })
    </script>
{% endblock otherjs%}

{% block mainfooter %}
{% endblock mainfooter%}

doctoronlinemaster/templates/doctoronlinemaster/m.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mpesa Test</title>
</head>
<body>
    <script>
        
    </script>
</body>
</html>